import type { Patch } from './types'

export const PATCHES: Patch[] = [
  {
    id: 'soft-hum',
    name: 'Soft Hum',
    blurb: 'Cabin whisper. Low motor presence without drama.',
    layers: [
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 52,
        hzPerMph: 0.55,
        hzPerThrottle: 18,
        idleGain: 0.12,
        peakGain: 0.38,
        filterHz: 420,
        filterPerThrottle: 280,
        q: 0.7,
      },
      {
        kind: 'tone',
        wave: 'triangle',
        baseHz: 104,
        hzPerMph: 1.1,
        hzPerThrottle: 36,
        idleGain: 0.04,
        peakGain: 0.18,
        filterHz: 900,
        filterPerThrottle: 500,
        q: 0.9,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.01,
        peakGain: 0.06,
        filterHz: 280,
        filterPerThrottle: 220,
        q: 0.5,
      },
    ],
  },
  {
    id: 'inverter-whine',
    name: 'Inverter Whine',
    blurb: 'High traction inverter whistle that climbs with speed.',
    layers: [
      {
        kind: 'tone',
        wave: 'sawtooth',
        baseHz: 380,
        hzPerMph: 4.2,
        hzPerThrottle: 120,
        idleGain: 0.02,
        peakGain: 0.22,
        filterHz: 1400,
        filterPerThrottle: 2200,
        q: 1.4,
      },
      {
        kind: 'tone',
        wave: 'triangle',
        baseHz: 760,
        hzPerMph: 8.4,
        hzPerThrottle: 240,
        idleGain: 0.01,
        peakGain: 0.12,
        filterHz: 2800,
        filterPerThrottle: 3000,
        q: 2.2,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.008,
        peakGain: 0.05,
        filterHz: 1800,
        filterPerThrottle: 2400,
        q: 0.8,
      },
    ],
  },
  {
    id: 'sci-fi',
    name: 'Sci-fi Drive',
    blurb: 'Warp-adjacent pulse. Fun for demos and night drives.',
    layers: [
      {
        kind: 'pulse',
        wave: 'square',
        baseHz: 90,
        hzPerMph: 1.6,
        hzPerThrottle: 70,
        idleGain: 0.05,
        peakGain: 0.28,
        filterHz: 700,
        filterPerThrottle: 1600,
        q: 3.2,
      },
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 220,
        hzPerMph: 3.2,
        hzPerThrottle: 140,
        idleGain: 0.03,
        peakGain: 0.2,
        filterHz: 1600,
        filterPerThrottle: 2800,
        q: 1.1,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.02,
        peakGain: 0.1,
        filterHz: 900,
        filterPerThrottle: 1800,
        q: 0.6,
      },
    ],
  },
]

export function patchById(id: string): Patch {
  const patch = PATCHES.find((p) => p.id === id)
  if (!patch) throw new Error(`Unknown patch: ${id}`)
  return patch
}
