import type { Patch } from './types'

/**
 * Procedural EV / motor patches.
 * All layers are synthesized in-browser (Web Audio) — no third-party samples.
 * Tune against Start → throttle → speed; pitch and timbre should track both.
 */
export const PATCHES: Patch[] = [
  {
    id: 'soft-hum',
    name: 'Soft Hum',
    blurb: 'Cabin whisper with a low motor floor that fills in as you roll.',
    layers: [
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 48,
        hzPerMph: 0.62,
        hzPerThrottle: 22,
        idleGain: 0.1,
        peakGain: 0.36,
        gainPerMph: 0.1,
        filterHz: 380,
        filterPerThrottle: 260,
        filterPerMph: 1.8,
        q: 0.7,
      },
      {
        kind: 'tone',
        wave: 'triangle',
        baseHz: 96,
        hzPerMph: 1.24,
        hzPerThrottle: 44,
        idleGain: 0.035,
        peakGain: 0.17,
        gainPerMph: 0.06,
        filterHz: 820,
        filterPerThrottle: 480,
        filterPerMph: 3.2,
        q: 0.9,
        detuneCents: 7,
      },
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 192,
        hzPerMph: 2.4,
        hzPerThrottle: 70,
        idleGain: 0.012,
        peakGain: 0.08,
        gainPerMph: 0.04,
        filterHz: 1400,
        filterPerThrottle: 900,
        filterPerMph: 6,
        q: 1.1,
        detuneCents: -5,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.012,
        peakGain: 0.055,
        gainPerMph: 0.025,
        filterHz: 260,
        filterPerThrottle: 200,
        filterPerMph: 2.5,
        q: 0.5,
      },
    ],
  },
  {
    id: 'inverter-whine',
    name: 'Inverter Whine',
    blurb: 'Traction inverter whistle that climbs hard with speed.',
    layers: [
      {
        kind: 'tone',
        wave: 'sawtooth',
        baseHz: 340,
        hzPerMph: 5.1,
        hzPerThrottle: 140,
        idleGain: 0.015,
        peakGain: 0.2,
        gainPerMph: 0.08,
        filterType: 'bandpass',
        filterHz: 1200,
        filterPerThrottle: 1800,
        filterPerMph: 14,
        q: 2.4,
      },
      {
        kind: 'tone',
        wave: 'triangle',
        baseHz: 680,
        hzPerMph: 10.2,
        hzPerThrottle: 260,
        idleGain: 0.008,
        peakGain: 0.11,
        gainPerMph: 0.05,
        filterType: 'bandpass',
        filterHz: 2400,
        filterPerThrottle: 2600,
        filterPerMph: 22,
        q: 3.2,
        detuneCents: 4,
      },
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 170,
        hzPerMph: 2.2,
        hzPerThrottle: 55,
        idleGain: 0.04,
        peakGain: 0.14,
        gainPerMph: 0.06,
        filterHz: 700,
        filterPerThrottle: 500,
        filterPerMph: 4,
        q: 0.8,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.006,
        peakGain: 0.045,
        gainPerMph: 0.02,
        filterType: 'bandpass',
        filterHz: 1600,
        filterPerThrottle: 2000,
        filterPerMph: 12,
        q: 1.2,
      },
    ],
  },
  {
    id: 'traction-growl',
    name: 'Traction Growl',
    blurb: 'Loaded motor body — deeper under throttle, denser with speed.',
    layers: [
      {
        kind: 'tone',
        wave: 'sawtooth',
        baseHz: 36,
        hzPerMph: 0.48,
        hzPerThrottle: 28,
        idleGain: 0.08,
        peakGain: 0.42,
        gainPerMph: 0.12,
        filterHz: 220,
        filterPerThrottle: 340,
        filterPerMph: 2.2,
        q: 1.1,
      },
      {
        kind: 'tone',
        wave: 'triangle',
        baseHz: 72,
        hzPerMph: 0.96,
        hzPerThrottle: 52,
        idleGain: 0.05,
        peakGain: 0.28,
        gainPerMph: 0.09,
        filterHz: 480,
        filterPerThrottle: 620,
        filterPerMph: 3.5,
        q: 1.3,
        detuneCents: -9,
      },
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 144,
        hzPerMph: 1.9,
        hzPerThrottle: 90,
        idleGain: 0.02,
        peakGain: 0.14,
        gainPerMph: 0.05,
        filterHz: 1100,
        filterPerThrottle: 1400,
        filterPerMph: 7,
        q: 1.6,
        detuneCents: 11,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.02,
        peakGain: 0.1,
        gainPerMph: 0.04,
        filterHz: 360,
        filterPerThrottle: 420,
        filterPerMph: 3,
        q: 0.6,
      },
    ],
  },
  {
    id: 'turbine-climb',
    name: 'Turbine Climb',
    blurb: 'Airy turbine character — pitch and air open with mph.',
    layers: [
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 220,
        hzPerMph: 6.5,
        hzPerThrottle: 90,
        idleGain: 0.02,
        peakGain: 0.18,
        gainPerMph: 0.12,
        filterType: 'bandpass',
        filterHz: 900,
        filterPerThrottle: 1100,
        filterPerMph: 18,
        q: 2.8,
      },
      {
        kind: 'tone',
        wave: 'triangle',
        baseHz: 440,
        hzPerMph: 13,
        hzPerThrottle: 160,
        idleGain: 0.01,
        peakGain: 0.1,
        gainPerMph: 0.08,
        filterType: 'bandpass',
        filterHz: 1800,
        filterPerThrottle: 2000,
        filterPerMph: 28,
        q: 3.6,
        detuneCents: 6,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.015,
        peakGain: 0.08,
        gainPerMph: 0.07,
        filterHz: 2400,
        filterPerThrottle: 1800,
        filterPerMph: 20,
        q: 0.7,
      },
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 55,
        hzPerMph: 0.7,
        hzPerThrottle: 20,
        idleGain: 0.05,
        peakGain: 0.16,
        gainPerMph: 0.05,
        filterHz: 300,
        filterPerThrottle: 200,
        filterPerMph: 1.5,
        q: 0.6,
      },
    ],
  },
  {
    id: 'gear-mesh',
    name: 'Gear Mesh',
    blurb: 'Reduction-gear texture — a metallic sing that tracks road speed.',
    layers: [
      {
        kind: 'tone',
        wave: 'sawtooth',
        baseHz: 180,
        hzPerMph: 3.8,
        hzPerThrottle: 40,
        idleGain: 0.02,
        peakGain: 0.14,
        gainPerMph: 0.1,
        filterType: 'bandpass',
        filterHz: 700,
        filterPerThrottle: 600,
        filterPerMph: 10,
        q: 4.2,
      },
      {
        kind: 'tone',
        wave: 'square',
        baseHz: 360,
        hzPerMph: 7.6,
        hzPerThrottle: 70,
        idleGain: 0.01,
        peakGain: 0.08,
        gainPerMph: 0.07,
        filterType: 'bandpass',
        filterHz: 1400,
        filterPerThrottle: 900,
        filterPerMph: 16,
        q: 5.5,
        detuneCents: -3,
      },
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 90,
        hzPerMph: 1.5,
        hzPerThrottle: 30,
        idleGain: 0.04,
        peakGain: 0.16,
        gainPerMph: 0.05,
        filterHz: 500,
        filterPerThrottle: 400,
        filterPerMph: 3,
        q: 0.9,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.01,
        peakGain: 0.05,
        gainPerMph: 0.03,
        filterType: 'bandpass',
        filterHz: 1100,
        filterPerThrottle: 800,
        filterPerMph: 8,
        q: 1.8,
      },
    ],
  },
  {
    id: 'cabin-whisper',
    name: 'Cabin Whisper',
    blurb: 'Near-silent EV presence — barely there until you lean on it.',
    layers: [
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 42,
        hzPerMph: 0.35,
        hzPerThrottle: 12,
        idleGain: 0.04,
        peakGain: 0.18,
        gainPerMph: 0.05,
        filterHz: 280,
        filterPerThrottle: 160,
        filterPerMph: 1.2,
        q: 0.55,
      },
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 84,
        hzPerMph: 0.7,
        hzPerThrottle: 24,
        idleGain: 0.015,
        peakGain: 0.08,
        gainPerMph: 0.03,
        filterHz: 560,
        filterPerThrottle: 280,
        filterPerMph: 2,
        q: 0.7,
        detuneCents: 5,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.008,
        peakGain: 0.03,
        gainPerMph: 0.015,
        filterHz: 200,
        filterPerThrottle: 140,
        filterPerMph: 1.5,
        q: 0.4,
      },
    ],
  },
  {
    id: 'sci-fi',
    name: 'Sci-fi Drive',
    blurb: 'Warp-adjacent pulse. Fun for demos and night drives.',
    layers: [
      {
        kind: 'pulse',
        wave: 'square',
        baseHz: 88,
        hzPerMph: 1.8,
        hzPerThrottle: 80,
        idleGain: 0.045,
        peakGain: 0.26,
        gainPerMph: 0.06,
        filterHz: 680,
        filterPerThrottle: 1500,
        filterPerMph: 8,
        q: 3.4,
      },
      {
        kind: 'tone',
        wave: 'sine',
        baseHz: 210,
        hzPerMph: 3.6,
        hzPerThrottle: 150,
        idleGain: 0.028,
        peakGain: 0.18,
        gainPerMph: 0.05,
        filterHz: 1500,
        filterPerThrottle: 2600,
        filterPerMph: 12,
        q: 1.2,
        detuneCents: 8,
      },
      {
        kind: 'tone',
        wave: 'triangle',
        baseHz: 420,
        hzPerMph: 7,
        hzPerThrottle: 200,
        idleGain: 0.012,
        peakGain: 0.1,
        gainPerMph: 0.04,
        filterType: 'bandpass',
        filterHz: 2200,
        filterPerThrottle: 2800,
        filterPerMph: 18,
        q: 2.4,
      },
      {
        kind: 'noise',
        baseHz: 0,
        hzPerMph: 0,
        hzPerThrottle: 0,
        idleGain: 0.018,
        peakGain: 0.09,
        gainPerMph: 0.03,
        filterHz: 860,
        filterPerThrottle: 1600,
        filterPerMph: 10,
        q: 0.6,
      },
    ],
  },
]

export function patchById(id: string): Patch {
  const patch = PATCHES.find((p) => p.id === id)
  if (!patch) throw new Error(`Unknown patch: ${id}`)
  return patch
}
